services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: /api
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend